server:
  port : 8081
  session:
    timeout: 6000000
eureka:
  client:
    serviceUrl:
      defaultZone : http://localhost:8761/eureka
spring:
  application:
    name: get-set-go-composite
  main:
    allow-bean-definition-overriding: true
gsg:
  core:
    url: http://localhost:8082/