server:
  port : 8082
eureka:
  client:
    serviceUrl:
      defaultZone : http://localhost:8761/eureka
spring:
  application:
    name: get-set-go-core
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        ddl-auto: none
        format_sql: true
        show_sql: true
        ejb.naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/gsg
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: root
    testWhileIdle: true
    validationQuery: SELECT 1
    max-active: 108
    maxIdle: 
    minEvictableIdleTimeMillis:
logging:
  level:
    org:
      hibernate:
        type: trace